# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

# Fabric Properties
minecraft_version=1.21.1
loader_version=0.16.14
loader_type=fabric

# Mod Properties
mod_id=banira_codex
mod_version=1.0.1
mod_name=\u9999\u8349\u5fd7(Banira Codex)
mod_authors=Tsuki Maaii
mod_desc=

sources_url=https://github.com/VanillaXin/BaniraCodex_MC
issues_url=https://github.com/VanillaXin/BaniraCodex_MC/issues
license=MIT

# Dependencies
fabric_version=0.116.13+1.21.1
modmenu_version=11.0.4
